# Generated by Django 2.1.7 on 2019-03-22 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='detail',
            fields=[
                ('pnr_no', models.IntegerField(primary_key=True, serialize=False)),
                ('no_of_passenger', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='station_detail',
            fields=[
                ('station_id', models.AutoField(primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='timetable_detail',
            fields=[
                ('timetable_id', models.AutoField(primary_key=True, serialize=False)),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('price', models.IntegerField()),
                ('distance', models.IntegerField()),
                ('train_class', models.CharField(max_length=30)),
                ('arrival_station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_station_id', to='booking.station_detail')),
                ('departure_station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_station_id', to='booking.station_detail')),
            ],
        ),
        migrations.CreateModel(
            name='train_detail',
            fields=[
                ('train_no', models.AutoField(primary_key=True, serialize=False)),
                ('train_name', models.CharField(max_length=30)),
                ('no_of_seat', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='train_seat_availability',
            fields=[
                ('seat_availability_id', models.AutoField(primary_key=True, serialize=False)),
                ('seat_availability', models.IntegerField()),
                ('date', models.DateField()),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.timetable_detail')),
            ],
        ),
        migrations.AddField(
            model_name='timetable_detail',
            name='train_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.train_detail'),
        ),
        migrations.AddField(
            model_name='detail',
            name='seat_availability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.train_seat_availability'),
        ),
        migrations.AddField(
            model_name='detail',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.timetable_detail'),
        ),
        migrations.AddField(
            model_name='detail',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.passenger_detail'),
        ),
    ]
