# Generated by Django 2.1.7 on 2019-03-17 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='station_detail',
            fields=[
                ('station_id', models.AutoField(primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='timetable_detail',
            fields=[
                ('timetable_id', models.AutoField(primary_key=True, serialize=False)),
                ('departure_time', models.TimeField()),
                ('price', models.IntegerField()),
                ('distance', models.IntegerField()),
                ('seat_availability', models.IntegerField()),
                ('arrival_station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_station_id', to='base.station_detail')),
            ],
        ),
        migrations.CreateModel(
            name='train_detail',
            fields=[
                ('train_no', models.AutoField(primary_key=True, serialize=False)),
                ('train_name', models.CharField(max_length=30)),
                ('no_of_seat', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='timetable_detail',
            name='train_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.train_detail'),
        ),
    ]
