# Generated by Django 2.1.7 on 2019-03-17 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable_detail',
            name='arrival_station_id',
        ),
        migrations.RemoveField(
            model_name='timetable_detail',
            name='train_no',
        ),
        migrations.DeleteModel(
            name='station_detail',
        ),
        migrations.DeleteModel(
            name='timetable_detail',
        ),
        migrations.DeleteModel(
            name='train_detail',
        ),
    ]
